# Generated by Django 5.1.3 on 2024-11-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_medicamento_foto_alter_tipomedicamento_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='medicamentos/', verbose_name='Foto del Medicamento'),
        ),
    ]
