# Generated by Django 5.1.3 on 2024-11-22 05:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0003_remove_citamedica_doctor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atencion',
            old_name='comentario',
            new_name='comentario_adicional',
        ),
        migrations.AddField(
            model_name='atencion',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Altura (m)'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='examen_fisico',
            field=models.TextField(blank=True, null=True, verbose_name='Examen Físico'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='examenes_enviados',
            field=models.TextField(blank=True, null=True, verbose_name='Examenes enviados'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='frecuencia_respiratoria',
            field=models.IntegerField(blank=True, null=True, verbose_name='Frecuencia Respiratoria(rpm)'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='presion_arterial',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Presión Arterial'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='pulso',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pulso (ppm)'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='saturacion_oxigeno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Saturación de Oxígeno (%)'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='sintomas',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Sintomas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atencion',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='tratamiento',
            field=models.TextField(verbose_name='Plan de Tratamiento'),
        ),
    ]
