# Generated by Django 5.1.3 on 2024-11-22 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0004_rename_comentario_atencion_comentario_adicional_and_more'),
        ('core', '0008_alter_medicamento_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('tipo_certificado', models.CharField(max_length=100, verbose_name='Tipo de Certificado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('diagnostico', models.ManyToManyField(related_name='certificados_diagnosticos', to='core.diagnostico', verbose_name='Diagnósticos')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor', verbose_name='Doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
            },
        ),
    ]
