# Generated by Django 5.1.3 on 2024-11-22 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0006_categoriaexamen_examen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costosatencion',
            name='servicios_adicionales',
        ),
        migrations.CreateModel(
            name='CostoAtencionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_servicio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo del Servicio')),
                ('costo_atencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costos_atenciones', to='attention.costosatencion', verbose_name='Costo Atención')),
                ('servicios_adicionales', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_adicionales', to='attention.serviciosadicionales', verbose_name='Servicios Adicionales')),
            ],
            options={
                'verbose_name': 'Costo detalle Atención',
                'verbose_name_plural': 'Costos detalles Atención',
            },
        ),
    ]
