# Generated by Django 5.1.3 on 2024-11-22 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0008_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='monto',
        ),
        migrations.AlterField(
            model_name='pago',
            name='costo_atencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attention.costosatencion', verbose_name='Costo Atención'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='examenes_medicos',
            field=models.ManyToManyField(blank=True, to='attention.examensolicitado', verbose_name='Examenes Médicos'),
        ),
    ]
